---
- name: Instalacao Pacotes base
  ansible.builtin.package:
    name:
      - htop
      - iotop
      - iftop
      - hdparm
      - traceroute
      - ipcalc
      - whois
      - dnsutils
      - net-tools
      - ncdu
      - bash-completion
      - curl
      - nmap
      - links
      - tcpdump
      - ethtool
      - iptraf-ng
      - exa 
      - python3-pip
      - golang
      - bat
      - ripgrep
      - pigz
      - locate
      - fzf
      - micro
      - zoxide
      - vim-nox
      - bpytop
      - grc     
    state: present
...
